"""schema.py - 127-column list + named references."""

EXPECTED_COLUMNS = [
    "SNL Institution Key",
    "Company Name",
    "City",
    "State",
    "Regulatory ID",
    "Parent Name",
    "Parent Regulatory ID",
    "Cert Number",
    "Total Assets ($000)",
    "Asset Growth Rate (%)",
    "Total Loans & Leases (Incl HFI & HFS) ($000)",
    "Loan Growth Rate (%)",
    "Total Loans & Leases/ Assets (%)",
    "Total Deposits (Incl Dom & For) ($000)",
    "Deposit Growth Rate (%)",
    "Loans/ Deposits (%)",
    "Memo: Full-time Employees (actual)",
    "Net Income ($000)",
    "ROAA (%)",
    "ROAE (%)",
    "Interest Income/ Avg Assets (%)",
    "Interest Expense/ Average Assets (%)",
    "Net Interest Income/ Avg Assets (%)",
    "Noninterest Income/ Average Assets (%)",
    "Noninterest Expense/ Avg Assets (%)",
    "Net Interest Margin (%)",
    "Yield/ Cost Spread (%)",
    "Operating Expense/ Operating Revenue (%)",
    "B3 or GRB: Tier 1 Common Capital (CET1) ($000)",
    "B3 or GRB: Tier 1 Common Capital (CET1) RB Ratio (%)",
    "Tier 1 Capital ($000)",
    "Tier 1 Risk-based Ratio (%)",
    "Leverage Ratio (%)",
    "B3 or GRB: Total Risk-Based Capital ($000)",
    "Risk Based Capital Ratio (%)",
    "Commercial RE Loans/ Total Risk-Based Capital (%)",
    "GRB: Total Equity Capital ($000)",
    "Equity/ Assets (%)",
    "Tang Equity/ Tang Assets (%)",
    "Common Dividends Declared/ Net Income (%)",
    "DOM: Construction & Land Development Loans/ Loans (%)",
    "DOM: Tot 1-4 Fam Loans/ Loans (%)",
    "DOM: Multifamily Loans/ Loans (%)",
    "DOM: Farm Loans/ Loans (%)",
    "DOM: CommRE(Nfarm/NRes)/ Loans (%)",
    "Foreign RE Lns/ Loans (%)",
    "CON: Real Estate Loans/ Loans (%)",
    "CON: Total C&I Loans/ Loans (%)",
    "CON: Total Cons Lns/ Loans (%)",
    "CON: Agricultural Prod/ Loans (%)",
    "CON:Other Loans/ Loans (%)",
    "CON: Total Leases/ Loans (%)",
    "CON: LESS: Unearn Inc/ Loans (%)",
    "Nonint-bear Dep/ Deposits (%)",
    "Transaction Accounts/ Deposits (%)",
    "MMDAs+Savings/ Deposits (%)",
    "Retail Time Dep/ Deposits (%)",
    "Jumbo Time Deposits/ Deposits (%)",
    "Foreign Deposits/ Deposits (%)",
    "Noncurrent Loans/ Loans (%)",
    "NPLs/ Loans (%)",
    "NPAs/ Assets (%)",
    "NPA Excluding Restructured Loans/ Total Assets (%)",
    "NPAs/ (Loans+OREO) (%)",
    "NPAs + 90 Days PD/ Assets (%)",
    "NPA+ Loans 90PD/ Tang Equity + LLR (%)",
    "Adj NPA+Adj Lns 90PD/ Tang Eq+LLR (%)",
    "Loan Loss Reserves/ Gross Loans (%)",
    "Reserves/ NPAs (%)",
    "Net Chargeoffs/ Avg Loans (%)",
    "Loan Loss Prov/ NCOs (%)",
    "Liquidity Ratio (%)",
    "Earning Assets/ IBL (%)",
    "Secs (FV)/ Secs (Amt Cost) (%)",
    "Pledged Secs/ Securities (%)",
    "Brokered Deposits/ Deposits (%)",
    "Jumbo Time Deposits/ Domestic Deposits (%)",
    "Yield on Loans (%)",
    "Yield on Debt and Equity Securities (%)",
    "Yield on Earning Assets (%)",
    "Cost of Interest Bearing Deposits (Point Avg) (%)",
    "Cost of Borrowings (%)",
    "Cost of Interest-bearing Liabilities (%)",
    "Cost of Funds (%)",
    "Deposit Efficiency (%)",
    "Realized Gain on HTM Securities ($000)",
    "Realized Gain on AFS Debt Securities ($000)",
    "U.S. Treasury Securities ($000)",
    "U.S. Agency & GSA Debt Secs ($000)",
    "Treasury, Agency, & GSA Debt ($000)",
    "State & Political: Total Securities ($000)",
    "Pass-Through RMBS: Issd by FNMA and FHLMC ($000)",
    "Pass-Through RMBS: Other ($000)",
    "Pass-Through RMBS: Total ($000)",
    "Other RMBS: Issd or Guar by GSEs ($000)",
    "Other RMBS: Coll by MBS Issd or Guar by GSEs ($000)",
    "Other RMBS: Other ($000)",
    "Other RMBS: Total ($000)",
    "Total: Residential Mortgage Backed Securities ($000)",
    "Pass-Thru CMBS: Issd or Guar by GSE ($000)",
    "Pass-Thru CMBS: Other ($000)",
    "Pass-Through CMBS ($000)",
    "Other CMBS: Issd or Guar by GSE ($000)",
    "Other CMBS: All Other ($000)",
    "Total: Commercial Mortgage Backed Securities ($000)",
    "Structured Financial Products ($000)",
    "FV: Invest Mutual Funds & Other Equity Securities ($000)",
    "Total Pass-Through RMBS Issd by Others ($000)",
    "Other Debt Secs ($000)",
    "Other Securities ($000)",
    "Total Securities ($000)",
    "CB: Unamortized Yld Adj on MBS ($000)",
    "MBS: Valuation Allowances ($000)",
    "Pass-Through RMBS: Guar by GNMA ($000)",
    "CDI: Valuation Allowance on all Other Secs ($000)",
    "Total Securities ($000).1",
    "Total Pass-Through RMBS Issd/Guar by GSEs ($000)",
    "Total Other RMBS Issd/Coll by GSEs ($000)",
    "Total: U.S. Agency and GSA Secs ($000)",
    "Total Securities HTM CB ($000)",
    "Str Fin Prd: TPS Finl Instn ($000)",
    "Str Fin Prd: TPS REIT ($000)",
    "Str Fin Prd: Corporate and Similar Loans ($000)",
    "Str Fin Prd: 1-4 MBS Issd or Guar by GSEs ($000)",
    "Str Fin Prd: 1-4 MBS Not Issd or Guar by GSEs ($000)",
    "Str Fin Prd: Diversified Pool ($000)",
    "Str Fin Prd: Other Collateral ($000)",
]
COL_INST_KEY = "SNL Institution Key"
COL_BANK = "Company Name"
COL_CITY = "City"
COL_STATE = "State"
COL_CERT = "Cert Number"
COL_ASSETS = "Total Assets ($000)"
COL_LOANS = "Total Loans & Leases (Incl HFI & HFS) ($000)"
COL_DEPOSITS = "Total Deposits (Incl Dom & For) ($000)"
COL_LOANS_DEP = "Loans/ Deposits (%)"
COL_LIQUIDITY = "Liquidity Ratio (%)"
COL_YIELD_EA = "Yield on Earning Assets (%)"
COL_NET_INCOME = "Net Income ($000)"
COL_FV_COST = "Secs (FV)/ Secs (Amt Cost) (%)"
COL_YIELD_SEC = "Yield on Debt and Equity Securities (%)"
COL_SECURITIES = "Total Securities ($000)"
COL_NIM = "Net Interest Margin (%)"
COL_COST_FUNDS = "Cost of Funds (%)"
COL_YIELD_LOANS = "Yield on Loans (%)"
COL_EQ_ASSETS = "Equity/ Assets (%)"
COL_LEVERAGE = "Leverage Ratio (%)"
COL_NPAS = "NPAs/ Assets (%)"
COL_PLEDGED = "Pledged Secs/ Securities (%)"
COL_BROKERED = "Brokered Deposits/ Deposits (%)"
COL_NONINT_DEP = "Nonint-bear Dep/ Deposits (%)"
